services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www/
    container_name: app_nginx